Feature: Auth code
    In order to present information of authorization code
    As a system admin
    I want to store information of auth code on a database

    Authorization code is an intermediery token to be generated by authorization server
    when a user authorize a client
    The client receives this token and exchange it for an access token

    Background:
        Given there are auth codes:
        | client_identifier | userIdentifier | expiryDateTime | scopes               | redirectUri                 | revoke | identifier                                                                       |
        | d86ed78f9824      | 11111          | P36M           | ["profile", "email"] | https://auth.local/callback | 0      | 3f732172ebd4124a4b5cc5ef13cf3d79dd2e9cc9eb6c8fc1990e71640ccb46feb8d2921a7dceb311 |
